GET http://localhost:1000

##############################################################################################################################################
### login
POST http://localhost:1000/auth/login
Content-Type: application/json

{
    "username": "thaithai11111111",
    "password": "123456789"
}

### register 
POST http://localhost:1000/auth/register
Content-Type: application/json

{
    "username": "deohieu",
    "email": "cascxcvzxv",
    "password": "cc"
}

### change password
PATCH http://localhost:1000/auth/changePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTcxNDE0MjM4OCwiZXhwIjoxNzE1NDM4Mzg4fQ.ZNSv-Aur5-UfD5a67cEQ9zSPfbz5UsJsZMYKqDh7v_8

{
    "oldPassword": "10000000",
    "newPassword": "123456789"
}

### log out
POST http://localhost:1000/auth/logout


##############################################################################################################################################
### post create
POST http://localhost:1000/post/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJpYXQiOjE3MTI5ODE4Mjd9.cZ4BjC1vQMEo-_qDNu_-Wvij5sNk8ltkTpPmoJp0eCo

{
    "caption": "this is test cloud",
    "hashtags": "dzco1ko2",
    "mentions": "mwahnga"
}

### get all post
GET http://localhost:1000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMjc1MDE3MX0._djjpG09p_1XjS30veovmc79HIj63DUaps0LtsCRfLk

### get 1 post
PUT http://localhost:1000/post/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMjcyMzkwNn0.OsoUTsO7aPzqm6qnecLrtNMfNKIl-8C_up-rKxNpLaE

{
    "caption": "test test cai lin",
    "hashtags": "tagcc",
    "mentions": "ha"
}

### delete post
DELETE http://localhost:1000/post/21
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMjcyMzkwNn0.OsoUTsO7aPzqm6qnecLrtNMfNKIl-8C_up-rKxNpLaE

### 
GET http://localhost:1000/post/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMjg0NTQwOH0.qad4zgSbNKNBOEY3_ph6h23kJD6F-mlY1iyg12cPFNU

### like 1 post
POST http://localhost:1000/post/11/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTcxMjkzNzEyNH0.xdvV3ZscmPAyFGTOZTrXvRpGbF_hBxJg_oz0tMgTfsU

### get all post of hashtag
GET http://localhost:1000/post/explore/dzco1ko2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMjgxMDI5NH0.Calk3G2DTPgeaO4AaQCG1TUExn-YH4wETGLuXKe5mZE


##################################################################################################################################
### get account edit
GET http://localhost:1000/account/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTcxNDE0MTk3OCwiZXhwIjoxNzE1NDM3OTc4fQ.2gwAJIG1P4hZj3dT3hFdeKDmnabLJX9b7RY3-CfTIAM

### udpate account edit
PUT http://localhost:1000/account/edit
Authorization: Bearer eyJcbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJpYXQiOjE3MTI5ODE4Mjd9.cZ4BjC1vQMEo-_qDNu_-Wvij5sNk8ltkTpPmoJp0eCo
Content-Type: application/json

{
    "username": "bbbbbbbbbbb",
    "email": "okkkko@gmail.com",
    "full_name": "qqqqnt",
    "bio": "qua sai ?"
}

### get all post of following
GET http://localhost:1000/post/feed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMjgxMDI5NH0.Calk3G2DTPgeaO4AaQCG1TUExn-YH4wETGLuXKe5mZE

###
POST http://localhost:1000/user/quangong/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMzExMzczNn0.xbcayKvVh0xzxmEj9SLNDsxKBYdjn-YkZcaycGrFcfo

hesdsls

###
GET http://localhost:1000/user/hels/followers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMzExMzA1NX0.5LLSz2E-4ceD0yi9yMaRSRfjhf6FzZ27QDITGeInI3A

###
GET http://localhost:1000/user/hels/following
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTcxMzExNDIwM30.UchNpMWGBie5fBnXeIOpR7XCtBewUyhKu4V2N-PhPvY

###
POST http://localhost:1000/search
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMzE1NDgzMn0.3K0kDQlDTLzlCvJscpmAXxuxe5YHH9GxaOsYS4AB5cM
Content-Type: application/json

{
    "term": "quang"
}

###
GET http://localhost:1000/activity
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMzI4MDA3MCwiZXhwIjoxNzE0NTc2MDcwfQ.Ha1KM0tUsGtpgulStNIpQrEJ0VCOs48yb4DpFJ6Luwg

###
PUT http://localhost:1000/activity
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxMzIzNTkzMH0.u0ybeJNLmUNV8CM-_no0wQYFxYU2cUl8YbD_Bs3cUco
